# Generated by Django 6.0.2 on 2026-05-22 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lc', '0008_alter_customuser_managers_lesson_homework_task'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('days', models.CharField(help_text='Masalan: Dushanba - Chorshanba - Juma', max_length=100)),
                ('time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_students', models.PositiveIntegerField(default=10)),
                ('current_students', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('lessons_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='courses.course')),
                ('mentor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lc_studygroup',
                'ordering': ['-start_date', 'name'],
            },
        ),
            ],
        ),
    ]
