# Generated by Django 6.0.4 on 2026-04-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0002_remove_course_total_sessions_course_price_formatted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
