# Generated by Django 6.0.2 on 2026-04-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0005_specialization_studygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='specialization',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
