# Generated by Django 6.0.2 on 2026-04-16 15:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0007_lessonwatchprogress'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_task',
            field=models.TextField(blank=True, help_text='Instructions for the homework', null=True),
        ),
    ]
